"use client";

import { useState } from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

import ChartVisualization from "./ChartVisualization";
import TableVisualization from "./TableVisualization";

import { 
  useCopilotReadable, 
  useCopilotAction,
} from "@copilotkit/react-core";
import { SearchResults } from "@/components/generative-ui/SearchResults";

// Import static data as fallback
import {
  page1_executiveSummary,
  page2_salesPerformance,
  page3_productPerformance,
  page4_marketingPerformance,
  page5_customerInsights,
  page6_operationalMetrics,
  dashboardConfig,
  getAllSections,
  calculateAggregatedMetrics,
} from "@/data/dashboard-data";

export function Dashboard() {
  const [activePage, setActivePage] = useState(1);
  const [dashboardData, setDashboardData] = useState<any>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationStatus, setGenerationStatus] = useState("");

  // Calculate metrics
  const aggregatedMetrics = dashboardData 
    ? calculateMetricsFromAIData(dashboardData)
    : calculateAggregatedMetrics();

  /* ================= COPILOT READABLE STATE ================= */
  useCopilotReadable({
    description: "Current dashboard configuration and state",
    value: {
      currentPage: activePage,
      hasDashboardData: !!dashboardData,
      isGenerating,
      availablePages: [
        { number: 1, title: "Executive Summary" },
        { number: 2, title: "Sales Performance" },
        { number: 3, title: "Product Analytics" },
        { number: 4, title: "Marketing" },
        { number: 5, title: "Customer Insights" },
        { number: 6, title: "Operations" },
      ],
      staticDataStructure: {
        executiveSummary: page1_executiveSummary.sections?.map(s => s.sectionTitle),
        salesPerformance: Object.keys(page2_salesPerformance.sections || {}),
        productPerformance: Object.keys(page3_productPerformance.sections || {}),
        marketingPerformance: Object.keys(page4_marketingPerformance.sections || {}),
        customerInsights: Object.keys(page5_customerInsights.sections || {}),
        operationalMetrics: Object.keys(page6_operationalMetrics.sections || {}),
      }
    },
  });

  /* ================= COPILOT ACTIONS ================= */
  
  // Main action to set dashboard data from agent
  useCopilotAction({
    name: "set_dashboard_data",
    description: "Set the complete dashboard data structure generated by the AI agent. This should include all pages and their sections with chart data.",
    parameters: [
      { 
        name: "data", 
        type: "object",
        description: "Complete dashboard data object with structure: { pages: { executive: {...}, sales: {...}, etc }, metadata: {...} }",
        required: true 
      }
    ],
    handler: async ({ data }) => {
      console.log("Received dashboard data from agent:", data);
      setDashboardData(data);
      setIsGenerating(false);
      setGenerationStatus("Dashboard generated successfully!");
      
      return {
        success: true,
        message: "Dashboard data has been updated",
        pagesLoaded: Object.keys((data as any).pages || {}).length
      };
    },
  });

  // Action to update generation status
  useCopilotAction({
    name: "update_generation_status",
    description: "Update the status message during dashboard generation",
    parameters: [
      { 
        name: "status", 
        type: "string",
        description: "Current status message",
        required: true 
      },
      {
        name: "isGenerating",
        type: "boolean",
        description: "Whether generation is in progress",
        required: false
      }
    ],
    handler: async ({ status, isGenerating: generating }) => {
      setGenerationStatus(status);
      if (typeof generating === 'boolean') {
        setIsGenerating(generating);
      }
      return { success: true };
    },
  });

  // Action to navigate pages
  useCopilotAction({
    name: "navigate_to_page",
    description: "Navigate to a specific dashboard page by number (1-6) or name",
    parameters: [
      { 
        name: "page", 
        type: "number",
        description: "Page number (1=Executive, 2=Sales, 3=Product, 4=Marketing, 5=Customer, 6=Operations)",
        required: true 
      }
    ],
    handler: async ({ page }) => {
      const pageNum = typeof page === 'number' ? page : parseInt(page);
      if (pageNum >= 1 && pageNum <= 6) {
        setActivePage(pageNum);
        const pageNames = ["Executive Summary", "Sales Performance", "Product Analytics", "Marketing", "Customer Insights", "Operations"];
        return {
          success: true,
          message: `Navigated to ${pageNames[pageNum - 1]}`,
          currentPage: pageNum
        };
      }
      return {
        success: false,
        message: "Invalid page number. Must be between 1 and 6."
      };
    },
  });

  // Reset to static data
  useCopilotAction({
    name: "reset_to_static_data",
    description: "Reset the dashboard to use the original static/demo data",
    parameters: [],
    handler: async () => {
      setDashboardData(null);
      setIsGenerating(false);
      setGenerationStatus("");
      return {
        success: true,
        message: "Dashboard reset to static data"
      };
    },
  });

  // Search action (disabled as specified)
  useCopilotAction({
    name: "searchInternet",
    available: "disabled",
    description: "Search business insights and market data",
    parameters: [{ name: "query", type: "string", required: true }],
    render: ({ args, status }) => (
      <SearchResults query={args.query ?? ""} status={status} />
    ),
  });

  /* ================= HELPER FUNCTIONS ================= */

  function calculateMetricsFromAIData(data: any) {
    try {
      const executivePage = data?.pages?.executive;
      if (!executivePage) return calculateAggregatedMetrics();

      const kpis = executivePage.sections?.find((s: any) => 
        s.sectionTitle?.toLowerCase().includes("kpi") || 
        s.sectionTitle?.toLowerCase().includes("performance")
      )?.data?.kpis || [];

      return {
        totalRevenue: kpis.find((k: any) => k.metric?.toLowerCase().includes("revenue"))?.value || 0,
        totalProfit: kpis.find((k: any) => k.metric?.toLowerCase().includes("profit"))?.value || 0,
        profitMargin: kpis.find((k: any) => k.metric?.toLowerCase().includes("margin"))?.value || 0,
        totalCustomers: kpis.find((k: any) => k.metric?.toLowerCase().includes("customer"))?.value || 0,
        avgMonthlyRevenue: 0
      };
    } catch (error) {
      console.error("Error calculating metrics from AI data:", error);
      return calculateAggregatedMetrics();
    }
  }

  /* ================= PAGE RENDERERS ================= */

  const renderPage1 = () => {
    const pageData = dashboardData?.pages?.executive || page1_executiveSummary;
    const kpiSection = pageData.sections?.[0];
    const kpis = kpiSection?.data?.kpis || [];

    return (
      <div className="grid gap-4 grid-cols-1 md:grid-cols-2 lg:grid-cols-4 w-full">
        {/* Generation Status */}
        {isGenerating && (
          <Card className="col-span-full bg-blue-50 border-blue-200">
            <CardContent className="flex items-center gap-3 py-4">
              <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-blue-600"></div>
              <p className="text-blue-900 font-medium">{generationStatus || "Generating dashboard..."}</p>
            </CardContent>
          </Card>
        )}

        {/* KPI Cards */}
        <div className="col-span-full grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3" data-kpi-section>
          {kpis.map((kpi: any, idx: number) => (
            <Metric 
              key={idx}
              label={kpi.metric} 
              value={
                kpi.format === "currency" 
                  ? `$${kpi.value.toLocaleString()}` 
                  : kpi.format === "percent" 
                  ? `${kpi.value}%` 
                  : (kpi.value ?? 0).toLocaleString()
              } 
            />
          ))}
        </div>

        {/* Rest of your existing charts... */}
        <Card className="col-span-full" data-chart-card>
          <CardHeader>
            <CardTitle>{pageData.sections?.[1]?.sectionTitle || "Revenue Trend"}</CardTitle>
            <CardDescription>{pageData.sections?.[1]?.description}</CardDescription>
          </CardHeader>
          <CardContent>
            <ChartVisualization
              chartType="line"
              data={pageData.sections?.[1]?.data?.timeSeries || []}
              xKey="month"
              yKeys={["revenue", "costs", "profit", "forecast"]}
              showTitle={false}
            />
          </CardContent>
        </Card>

        {/* Add rest of your charts from the original code */}
      </div>
    );
  };

  // Include all other page renderers (renderPage2-6) from your original hardcoded code
  // ... (copy from original)

  const pages = [
    { number: 1, title: "Executive Summary", render: renderPage1 },
    // Add other pages...
  ];

  return (
    <div className="w-full space-y-4">
      {/* Page Navigation */}
      <Card data-navigation-card>
        <CardHeader>
          <CardTitle>Dashboard Navigation</CardTitle>
          <CardDescription>
            {dashboardData ? "AI-Generated Dashboard" : "Static Demo Dashboard"}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex flex-wrap gap-2">
            {pages.map((page) => (
              <button
                key={page.number}
                onClick={() => setActivePage(page.number)}
                className={`px-4 py-2 rounded-lg font-medium text-sm transition-all ${
                  activePage === page.number
                    ? "bg-blue-600 text-white shadow-md"
                    : "bg-gray-100 text-gray-700 hover:bg-gray-200"
                }`}
              >
                <span className="font-bold">{page.number}.</span> {page.title}
              </button>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Active Page Content */}
      {pages.find((p) => p.number === activePage)?.render()}
    </div>
  );
}

function Metric({ label, value }: { label: string; value: string }) {
  return (
    <div className="bg-white p-3 rounded-lg border border-gray-100 shadow-sm hover:shadow-md transition-shadow">
      <p className="text-xs text-gray-500 font-medium">{label}</p>
      <p className="text-xl font-semibold text-gray-900 mt-1">{value}</p>
    </div>
  );
}